server:
  port: 8001
spring:
  application:
    name: user-provide8001
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: 123456
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-user-provide8001
    prefer-ip-address: true
info:
  bulid.artifactId: $project.artifactId$
  bulid.version: $project.version$
  server.name: user-provide8001

